on:
  push:
    branches:
      - '**'
  pull_request:
      types: [closed]

name: Bundle and Publish Sources
jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: npm install

      - if: steps.extract_branch.outputs.branch != 'master' && steps.extract_branch.outputs.branch != 'main' 
        run: npm run bundle --folder=${{ steps.extract_branch.outputs.branch }}
        
      - if: steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'main' 
        run: npm run bundle

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: bundles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
